// AUTO-GENERATED from Stitch — DO NOT modify layout or CSS
// Screen: Customer Editor - ReturnFlow Desk
// 
// AGENT INSTRUCTIONS:
// 1. DO NOT change className values or layout structure
// 2. Add useState for dynamic values (replace hardcoded text)
// 3. Wire interactive controls through the typed actions prop
// 4. Replace placeholder data with props/state

import { ArrowLeft, Circle, Info } from "lucide-react";


export type CustomerEditorReturnflowDeskActionId = "cancel-edit-1" | "save-return-2";

export interface CustomerEditorReturnflowDeskProps {
  actions?: Partial<Record<CustomerEditorReturnflowDeskActionId, () => void>>;
}

export function CustomerEditorReturnflowDesk({ actions }: CustomerEditorReturnflowDeskProps) {
  return (
    <>
      {/* Task Header (Simplified, isolated context) */}
      <header className="w-full bg-surface-container-lowest border-b border-outline-variant px-margin-page h-14 flex items-center justify-between sticky top-0 z-10 shrink-0">
      <div className="flex items-center gap-stack-compact">
      <ArrowLeft className="text-on-surface-variant cursor-pointer hover:text-on-surface transition-colors" aria-hidden={true} focusable="false" />
      <h1 className="font-headline-sm text-headline-sm text-on-surface ml-2">Edit Customer Return</h1>
      </div>
      <div className="flex items-center gap-gutter">
      {/* Unsaved Changes Badge */}
      <div className="flex items-center gap-unit bg-tertiary-fixed text-on-tertiary-fixed-variant px-2 py-1 rounded font-table-data text-table-data">
      <Circle className="text-[16px]" aria-hidden={true} focusable="false" />
                      Unsaved Changes
                  </div>
      <div className="h-6 w-px bg-outline-variant"></div>
      <button className="text-on-surface-variant hover:text-on-surface font-table-data text-table-data transition-colors" type="button" data-action-id="cancel-edit-1" onClick={actions?.["cancel-edit-1"]}>
                      Cancel Edit
                  </button>
      <button className="bg-primary text-on-primary h-8 px-4 rounded font-table-data text-table-data hover:opacity-90 transition-opacity" type="button" data-action-id="save-return-2" onClick={actions?.["save-return-2"]}>
                      Save Return
                  </button>
      </div>
      </header>
      {/* Main Canvas */}
      <main className="flex-1 overflow-y-auto p-margin-page flex justify-center items-start">
      <div className="w-full max-w-3xl flex flex-col gap-margin-page">
      {/* Unsaved Changes Banner (More prominent) */}
      <div className="bg-surface-container-low border border-outline-variant rounded-lg p-4 flex items-start gap-stack-compact">
      <Info className="text-on-surface-variant mt-0.5" aria-hidden={true} focusable="false" />
      <div>
      <h3 className="font-table-data text-table-data text-on-surface">You have unsaved changes</h3>
      <p className="font-body-sm text-body-sm text-on-surface-variant mt-1">Please save your work before leaving this page to prevent data loss.</p>
      </div>
      </div>
      {/* Form Card */}
      <div className="bg-surface-container-lowest border border-outline-variant rounded-lg shadow-sm">
      <form className="p-margin-page flex flex-col gap-margin-page">
      {/* Section: System Info (Readonly) */}
      <div className="flex flex-col gap-stack-dense">
      <label className="font-table-data text-table-data text-on-surface-variant">Order ID <span className="text-error">*</span></label>
      <input className="h-8 w-full md:w-1/2 bg-surface-container text-on-surface-variant border border-outline-variant rounded px-2 font-table-data text-table-data cursor-not-allowed select-none focus:outline-none" readOnly={true} type="text" value="ORD-8823-XYZ" />
      <p className="font-body-sm text-body-sm text-on-surface-variant mt-1">Generated by source system. Cannot be modified.</p>
      </div>
      <div className="h-px w-full bg-surface-variant"></div>
      {/* Section: Customer Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-gutter">
      <div className="flex flex-col gap-stack-dense">
      <label className="font-table-data text-table-data text-on-surface" htmlFor="customer_name">Customer Name <span className="text-error">*</span></label>
      <input className="h-8 w-full bg-surface-container-lowest text-on-surface border border-outline-variant rounded px-2 font-body-sm text-body-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-shadow" id="customer_name" type="text" defaultValue="Michael Chen" />
      </div>
      <div className="flex flex-col gap-stack-dense">
      <label className="font-table-data text-table-data text-on-surface" htmlFor="customer_email">Customer Email <span className="text-on-surface-variant font-normal ml-1">(Optional)</span></label>
      <input className="h-8 w-full bg-surface-container-lowest text-on-surface border border-outline-variant rounded px-2 font-body-sm text-body-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-shadow" id="customer_email" type="email" defaultValue="m.chen@example.com" />
      </div>
      </div>
      <div className="h-px w-full bg-surface-variant"></div>
      {/* Section: Return Specifics */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-gutter">
      <div className="flex flex-col gap-stack-dense">
      <label className="font-table-data text-table-data text-on-surface" htmlFor="return_reason">Return Reason <span className="text-error">*</span></label>
      <select className="h-8 w-full bg-surface-container-lowest text-on-surface border border-error rounded px-2 font-body-sm text-body-sm focus:outline-none focus:ring-2 focus:ring-error focus:border-transparent appearance-none transition-shadow" id="return_reason" defaultValue="">
      <option disabled={true} value="">Select a reason...</option>
      <option value="defective">Defective Product</option>
      <option value="wrong_item">Wrong Item Shipped</option>
      <option value="not_needed">No Longer Needed</option>
      </select>
      {/* Validation Message */}
      <div className="flex items-center gap-unit mt-1 text-error">
      <Circle className="text-[14px]" aria-hidden={true} focusable="false" />
      <span className="font-label-caps text-label-caps">Return Reason is required</span>
      </div>
      </div>
      <div className="flex flex-col gap-stack-dense">
      <label className="font-table-data text-table-data text-on-surface" htmlFor="inspection_lane">Inspection Lane Assignment <span className="text-error">*</span></label>
      <select className="h-8 w-full bg-surface-container-lowest text-on-surface border border-outline-variant rounded px-2 font-body-sm text-body-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent appearance-none transition-shadow" id="inspection_lane" defaultValue="lane_b">
      <option value="lane_a">Lane A (Standard)</option>
      <option value="lane_b">Lane B (Electronics)</option>
      <option value="lane_c">Lane C (Heavy Goods)</option>
      </select>
      <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-on-surface-variant hidden">
      {/* Custom chevron could go here if appearance-none is removed, but standard select is fine for dense UI */}
      </div>
      </div>
      </div>
      <div className="h-px w-full bg-surface-variant"></div>
      {/* Section: Notes */}
      <div className="flex flex-col gap-stack-dense">
      <label className="font-table-data text-table-data text-on-surface" htmlFor="exception_notes">Exception Notes <span className="text-on-surface-variant font-normal ml-1">(Optional)</span></label>
      <textarea className="w-full bg-surface-container-lowest text-on-surface border border-outline-variant rounded p-2 font-body-sm text-body-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-shadow resize-y" id="exception_notes" rows={3} defaultValue="Customer indicated packaging was damaged upon arrival, but product appears intact on initial scan." />
      </div>
      </form>
      </div>
      </div>
      </main>
    </>
  );
}
